name: Deploy

on:
  push:
    branches: [main]

  repository_dispatch:
    types: [directus.deploy]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install
      - run: |
          touch .env.local
          echo NEXT_PUBLIC_GOOGLE_CALENDAR_API_KEY=${{secrets.NEXT_PUBLIC_GOOGLE_CALENDAR_API_KEY}} >> .env.local
          echo NEXT_PUBLIC_GOOGLE_ANALYTICS_ID=${{secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID}} >> .env.local
          echo DIRECTUS_TOKEN=${{secrets.DIRECTUS_TOKEN}} >> .env.local
          npm run build
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: aws s3 sync ./out s3://srblife.com

      - run: aws cloudfront create-invalidation --distribution-id=$CLOUDFRONT_DISTRIBUTION_ID --paths '/*'
        env:
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
